### ISSUE TITLE
[Build] SDL Framework causes CMake to fail

### ISSUE THREAD

**Issue by Ghostkwebb** [shinra-electric/Arm-Build-Script-for-RPCS3#10] opened 2024-09-06 08:13 UTC
Device: Apple M1 Pro 2021
OS: macOS Sonoma 14.6.1

[cmd_log.txt](https://github.com/user-attachments/files/16904892/cmd_log.txt)

I get this error everytime pls help :)

**Comment by Ghostkwebb** [comment] 2024-09-06 08:16
(base) ╭─ghostkwebb@Sharads-MacBook-Pro ~/Desktop/PS3/RPCS3-Arm-Build-Script  ‹main*› 
╰─➤  brew info sdl2
==> sdl2: stable 2.30.7 (bottled), HEAD
Low-level access to audio, keyboard, mouse, joystick, and graphics
https://www.libsdl.org/
Installed
/opt/homebrew/Cellar/sdl2/2.30.7 (94 files, 6.5MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-09-05 at 02:47:43
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/s/sdl2.rb
License: Zlib
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 75,585 (30 days), 218,275 (90 days), 719,112 (365 days)
install-on-request: 10,989 (30 days), 32,724 (90 days), 117,207 (365 days)
build-error: 6 (30 days)

**Comment by shinra-electric** [comment] 2024-09-06 09:09
The problem is that the script is using the SDL2 framework, rather than Homebrew SDL2. 

A quick fix would be to remove the SDL2 framework from `/Library/Frameworks/`. 

But I've seen this issue before in one of my other scripts when people have the SDL Framework installed. I can push a fix after I remind myself how I got around it.

**Comment by Ghostkwebb** [comment] 2024-09-06 09:17
> The problem is that the script is using the SDL2 framework, rather than Homebrew SDL2.
> 
> A quick fix would be to remove the SDL2 framework from `/Library/Frameworks/`.
> 
> But I've seen this issue before in one of my other scripts when people have the SDL Framework installed. I can push a fix after I remind myself how I got around it.

I thank you for your efforts!
So you are telling me to remove sdl2 from frameworks right?
Let me try that and see what happens.

**Comment by shinra-electric** [comment] 2024-09-06 09:19
I've just pushed a workaround to the script, can you try it and let me know if it works?

**Comment by Ghostkwebb** [comment] 2024-09-06 09:30
I'm not sure what happened this time but it got further

[console.log](https://github.com/user-attachments/files/16905855/console.log)

**Comment by shinra-electric** [comment] 2024-09-06 09:39
The SDL issue was fixed, but I'm not sure what the problem is this time.... 
It might be with libpng, I'm not sure. 

I'll need more time to go over the log, and I might have more questions for you.

**Comment by Ghostkwebb** [comment] 2024-09-06 09:41
I thank you very much for your efforts!

**Comment by shinra-electric** [comment] 2024-09-06 09:44
I can see from the log you have `libpng` `1.6.43` installed, but CMake is declaring `1.4.12`, this might be a clue. 

If you go to `/opt/homebrew/Cellar/libpng` do you see multiple versions there?

**Comment by Ghostkwebb** [comment] 2024-09-06 09:49
I only see version 1.6.43

<img width="920" alt="image" src="https://github.com/user-attachments/assets/c74a7fed-0c69-4594-92a6-39fffa33d933">

Do I need to download 1.4.12?

**Comment by shinra-electric** [comment] 2024-09-06 09:53
No, you should be on the newer one. 
but CMake is finding an older one somehow….

**Comment by shinra-electric** [comment] 2024-09-06 10:22
One thing you can try is to not use homebrew's `libpng`

You'd have to uncomment out libpng on line `120` (and add a `\` after it). 
Then on line `170` change `-DUSE_SYSTEM_LIBPNG` to `OFF` 

Let me know how that goes. 

If it doesn't work I'll close this issue and open a new one, since the SDL issue is fixed.

**Comment by Ghostkwebb** [comment] 2024-09-06 10:44
So well........

Screenshots to show u and confirm that I haven't any mistakes even though it's a simple task

<img width="524" alt="image" src="https://github.com/user-attachments/assets/6c64e43b-c943-4843-8bf9-fffbdc5e7d97">

<img width="630" alt="image" src="https://github.com/user-attachments/assets/50608388-6b7c-4035-88cb-cfa8578b6cf6">

And sorry to be the bearer of bad news but it didn't work

[console.txt](https://github.com/user-attachments/files/16906686/console.txt)

**Comment by shinra-electric** [comment] 2024-09-06 12:15
I forgot to mention, can you delete your rpcs3 folder first?

**Comment by Ghostkwebb** [comment] 2024-09-06 12:16
I'm dumb uk :)

**Comment by Ghostkwebb** [comment] 2024-09-06 12:23
I'm the bearer of bad news aren't I

[console_new.txt](https://github.com/user-attachments/files/16907729/console_new.txt)

**Comment by Ghostkwebb** [comment] 2024-09-06 13:01
I removed everything and did it fully again just in case with the script changes ofc just in case

[printfcmd.txt](https://github.com/user-attachments/files/16908338/printfcmd.txt)

**Comment by Ghostkwebb** [comment] 2024-09-07 15:28
Any updates on this sir?

**Comment by shinra-electric** [comment] 2024-09-08 06:57
No, I haven’t had much time to look at this further. It’s hard to debug because I can’t reproduce it. 

As I mentioned above, I’ll close this issue and open a new one, since it’s not about SDL anymore.

**Closed as completed by shinra-electric** 2024-09-08 06:57 UTC
